#INDRODUCTION TO PYTHON

In [2]:
2+2 

4

In [3]:
# Displaying output in python

print(2+2)

4


In [4]:
input("Enter your Name: ")

Enter your Name: Chibuzo


'Chibuzo'

In [5]:
print("Python is easy")

Python is easy


In [6]:
# Variable are container for storing information
num = 2+2
# 1 Variables cannot start with numbers instead use letters ot underscore _
# number = 2+2

# 2 Variable can not use reserved of key words
# input = 5

# 3. Avoid spaces in between variable use underscore instead of space
# first_name ="Chibuzo"

# 4. do not use symbol in the variable name

# 5. use meaningful and descriptive words
# use Total Profit = 40 instead of tp = 40


In [9]:
X

4

In [10]:
print(X)

4


In [74]:
# Data type
 # strings sequence of character. it is denoted by "", """  """
 # strings are immutable: cannot add or remove from it
address = "35 Jose street, ontario"
gender = "Female"
message = """ 
Dear John,
How are you doing?
Python is easy as you can see
"""
 # lists 
 # dictionary
 # sets
# turple
# number
# boolean
# none

In [75]:
print(address)

35 Jose street, ontario


In [5]:
address[3]

'J'

In [6]:
address[-1]

'o'

In [7]:
address[22
    ]

'o'

In [8]:
# slicing - accessing more than one character
address[16:23]

'onatrio'

In [9]:
address[:]

'35 Jose street, onatrio'

In [11]:
address[:7]

'35 Jose'

In [12]:
address[::2]

'3 oesre,oaro'

In [13]:
address[3:7]

'Jose'

In [14]:
numbers = "123456789"
numbers[::2]    (when using positive the begining index is selected)

'13579'

In [15]:
numbers[1::2]

'2468'

In [30]:
address[-8:]

' onatrio'

In [31]:
address[-7:-1]

'onatri'

In [35]:
numbers1 = "A:1, B:2, C:3"
numbers1[::5]

'ABC'

In [56]:
data = "123456789"
data[:0:-1]    (when using negative the stopping index is not selected )

'98765432'

In [57]:
data[-1:-9:-1]

'98765432'

In [60]:
# counting number of characters in a string
len(data)

9

In [61]:
# string methods
address

'35 Jose street, onatrio'

In [63]:
address.upper()

'35 JOSE STREET, ONATRIO'

In [65]:
address.casefold()

'35 jose street, onatrio'

In [81]:
address.index("ontario")

16

In [82]:
address.count("o")

3

In [84]:
address.endswith("y")

False

In [85]:
address.startswith("3")

True

In [86]:
address.find("J")

3

In [88]:
address.replace("ontario", "Lagos")

'35 Jose street, Lagos'

In [90]:
username = "   Wale"
username

'   Wale'

In [91]:
username.strip()

'Wale'

In [92]:
username.lstrip()

'Wale'

In [93]:
username.rstrip()

'   Wale'

In [94]:
username.rsplit()

['Wale']

In [97]:
address.split()

['35', 'Jose', 'street,', 'ontario']

In [100]:
colors = ["brown", "blue", "black"]

In [103]:
colors.pop(0)

'brown'

In [105]:
colors.pop()

'black'

In [106]:
colors

['blue']

In [111]:
colors.insert(0,"red")

In [112]:
colors

['red', 'blue', 'red']

In [115]:
colors.remove("red")

In [116]:
colors

['blue']

In [118]:
colors.insert(0,"red")

In [119]:
colors.insert(3,"green")

In [120]:
colors

['red', 'blue', 'green']

In [123]:
colors.append("black")

In [124]:
print(colors)

['red', 'blue', 'green', 'black']


In [127]:
new_colors = colors.copy()

In [128]:
new_colors

['red', 'blue', 'green', 'black']

In [129]:
colors.extend([1,2,3,4]) # used to combine two list

In [130]:
colors

['red', 'blue', 'green', 'black', 1, 2, 3, 4]

In [131]:
colors.reverse()

In [132]:
colors

[4, 3, 2, 1, 'black', 'green', 'blue', 'red']

In [135]:
colors.remove(1)

In [136]:
colors

[4, 3, 2, 'black', 'green', 'blue', 'red']

In [137]:
colors = ['red', 'blue', 'green', 'black']

In [13]:
# Dictionary like creating table in SQL
staff = {
    "name":"wale", "age": 18,
    "address":{"state":"Lagos", "country": "Nigeria"}

}

In [11]:
staff["name"]

'wale'

In [14]:
staff["address"]["country"]

'Nigeria'

In [20]:
staff

{'name': 'wale',
 'age': 18,
 'address': {'state': 'Lagos', 'country': 'Nigeria'},
 'gender': 'Male'}

In [18]:
staff["gender"] = "Male"

In [19]:
staff

{'name': 'wale',
 'age': 18,
 'address': {'state': 'Lagos', 'country': 'Nigeria'},
 'gender': 'Male'}

In [22]:
staff["age"]

18

In [27]:
staff.get("address")

{'state': 'Lagos', 'country': 'Nigeria'}

In [28]:
staff.keys()

dict_keys(['name', 'age', 'address', 'gender'])

In [29]:
staff.values()

dict_values(['wale', 18, {'state': 'Lagos', 'country': 'Nigeria'}, 'Male'])

In [30]:
staff.items()

dict_items([('name', 'wale'), ('age', 18), ('address', {'state': 'Lagos', 'country': 'Nigeria'}), ('gender', 'Male')])

In [31]:
staff.pop("gender")

'Male'

In [32]:
staff

{'name': 'wale',
 'age': 18,
 'address': {'state': 'Lagos', 'country': 'Nigeria'}}

In [33]:
staff.popitem()

('address', {'state': 'Lagos', 'country': 'Nigeria'})

In [34]:
staff

{'name': 'wale', 'age': 18}

In [36]:
staff.popitem()

('age', 18)

In [37]:
staff

{'name': 'wale'}

In [41]:
staff.update({"age":21})

In [43]:
staff

{'name': 'wale', 'age': 21}

In [47]:
staff.update({"postcode": 1234})

In [45]:
staff

{'name': 'wale', 'age': 21, 'postcode': '01234'}

In [48]:
staff.setdefault("status", "Single")

'Single'

In [49]:
staff

{'name': 'wale', 'age': 21, 'postcode': 1234, 'status': 'Single'}

In [54]:
staff.update({"email": "wale@gmail.com"})

In [55]:
staff

{'name': 'wale',
 'age': 21,
 'postcode': 1234,
 'status': 'Single',
 'email': 'wale@gmail.com'}

In [1]:
greeting = "Welcome to python"

In [4]:
greeting[11:17]

'python'

In [10]:
sample = "My name is Wale"

In [11]:
sample[:-5:-1]

'elaW'

In [12]:
# 4 Rules for naming a variable
# 1. Must not start with numeric or numbers can start with underscore
# 2. Must not use keywords or reserved words
# 3. Must not have space in between use underscore instead
# 4. do not use symbol

In [29]:
 name = "Emmanuel Oha"

In [44]:
  age = "13"

In [47]:
print("My name is " + name)
print(type(name))
print("I am " + age + " " + "years old")
print(type("age"))

My name is Emmanuel Oha
<class 'str'>
I am 13 years old
<class 'str'>


In [3]:
record = {'k1':[{'nest_key':['this is deep',['blacktech']]}]}

In [19]:
record["k1"][0]["nest_key"][1]

['blacktech']

In [154]:
# Python Assignment
# 1. 
greeting = "Welcome to python"
# print out "python" from the code above using slicing
greeting [-6:]
greeting[11:]

# 2. 
sample = 'My Name is Wale'
# bring out the wale in the sample above in reverse eg. "elaW"
# sample[:10:-1]
sample[:-5:-1]


# 3. mention 4 rules for naming a variable
# 4. 
# Create 2 variables, one for storing your name and the other for storing your age.
# Assuming your age is 18, print out eg. My name is wale. I am 18 years old.
# where Wale represents your name and 18 represents your age
name = "Chibuzo"
age = 18
print(f"My name is {name}. I am {age} years old")
print("My name is", name, "I am ", age ,"years old")

# 5. print out blacktech from the record below
record ={'k1':[{'nest_key':['this is deep',['blacktech']]}]}
record["k1"][0]["nest_key"][1][0]

My name is Chibuzo. I am 18 years old
My name is Chibuzo I am  18 years old


'blacktech'

In [140]:
# More data types
    # Tuple -- is for storing data that cannot be changed, its denoted by ()
days_of_the_week = ("Monday", "Tuesday", "Wednessday")
days_of_the_week
    # sets -- used to store unique data values
numbers ={1,2,3,1,1,1,2,2,2,2,3,3,3,3,3,3}
print(numbers)
    # numbers 
    # none

{1, 2, 3}


In [144]:
x = {1,2,3}
y = {3,4,5}
# Union - combination of what is in x and y
x.union(y)
# intersection--  what is common to x and y
x.intersection(y)

{3}

In [159]:
# strings = "how are you doing" 
# list = [1,2,3,3]
# dictionary = {"name":"wale", "age": "18"}
# tuple = (1,2,3,4)
# sets = {1,2,3,4}
# difference -what is in x that is not in y or what is in y that is not in x
# x.difference(y)
# y.difference(x)
# symetrical difference -- what is in x and not in y and what is in y that is not in x
# x.symmetric_difference(y)
# add --is used for including values
# y.add(8)
# y
# subset -- is having an item in another item
x = {1}
y = {1,2,3}
x.issubset(y)

True

In [164]:
# Boolean = True or False
is_admin = True
if is_admin == False:
    print("you can modify user data")
else:
    print("You need to be an admin to perform operation")
    


You need to be an admin to perform operation


In [166]:
# numbers
age = 18 
salary = 50000.1234527 
type(age)

int

In [167]:
type(salary)

float

In [171]:
import math
math.pi

3.141592653589793

In [173]:
# formating floating number
print("%.3f" %salary)

50000.123


In [174]:
print("%.2f" %math.pi)

3.14


In [ ]:
total_cost+price = None

In [190]:
# Operators -- are symbols used to perform operations
# arithmetic +, -, /,*,//,%.**
5 + 6
7 - 3
3 * 5
5 // 2  #floor division
8 % 3
# 3 ** 2
# comparism operator <, >, <=, >=, ==, !=
# Logical operator  and, or , not
# assignment operator +=, -=, /=, *=, %=
x = 5
y = 2
x *= y
x
x -= y
x
# membership operator (in) to check if an item belong to a list and you normally use in operator
fruits = ["apple", "orange", "pawpaw"]
"wale" in fruits
# identity operator (is) for checking if two values are the same

5 is 4

<>:23: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:23: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\CEO\AppData\Local\Temp\ipykernel_2444\3523947666.py:23: SyntaxWarning: "is" with a literal. Did you mean "=="?
  5 is 4


False

In [192]:
#control flow is to a condition and specify what happens if it is met or not
age = 18
if age >= 18:
    print("you can vote")
else:
    print("Not eligible")
    


you can vote


In [211]:
number = 5
if number > 0:
    print("Positive")
elif number < 0:
    print("Negative")
else: print("Invalid")
       

Positive


In [124]:
number = input(number)
match(number):
    case " number > 0":
        print("Positive")
    case "number < 0":
        print("Negative")
    case _:
        print("Invalid")

132
Invalid


In [227]:
grade = input("enter grade")

match(grade.upper()):
    case "A":
        print("Excellent")
    case "B":
        print("Good")
    case _:
        print("Invalid")

enter gradeb
Good


In [238]:
# Loop is used for iteration (repeating a task) until certain condition is met
# while loop used when you dont know how man iteration is to be done
 #it has 4 condition
#     1. initial value
#     2. condition
#     3. action
#     4. increament
# for loop

x = 1
while x <= 10:
    print(x)
    x += 1
    
x = 2
while x <= 10:
    print(x)
    x += 2


1
2
3
4
5
6
7
8
9
10
2
4
6
8
10


In [245]:
username = input("enter username")
password = input("enter password")
stored_username = "wale"
stored_password = "123456"
if username == stored_username and len(username) >3:
    if password == stored_password:
        print("Login Successful")
    else:
        print("wrong password")
else:
    print("wrong username")

enter usernamewale
enter password123456
Login Successful


In [251]:
username = input("enter username")
password = input("enter password")
stored_username = "wale"
stored_password = "123456"
if username == stored_username and len(username) >3 and password == stored_password:
            print("Login Successful")
else:
    print("wrong credentials")

enter usernameWale
enter password123456
wrong credentials


In [255]:
# for loop
numbers = [1,2,3,4,5]
for i in numbers:
    print(i)

1
2
3
4
5


In [9]:
numbers = [1,2,3,4,5]
for i in numbers:
    print(i)

1
2
3
4
5


In [259]:
# print even numbers
# As a layman follow this method
# go through the numbers
# check each number if they are divisible by 2 without remainder 
# show the ones that meet the condition
numbers = [1,2,3,4,5]
for i in numbers:
    if i % 2 == 0:
        print(i)

2
4


In [ ]:
1. create a program that displays a multiplication table
eg. 2 x 1 = 2
    2 x 2 = 4
up to 2 x 12 = 24

NB: Do not write out the table one by one. Use loop.


2. create a program that finds the largest of 3 numbers

3.  create a program that take a score and show the grade using if else or match case:
90 - 100 ("Grade A")
70 - 89  ("Grade B")
50 - 69 ("Grade c")
30 - 49 ("Grade E")
0 - 29  ("Grade E")

so if I enter any number as score it show the corresponding grade

3. Create a program that accepts 2 numbers and an operator eg. 5 6, +
then perform an operation based on what the user enters eg 5 + 6
if the user enters 2, 8, * it should return 2 * 8
and show the answer in console

4. create a program that removes a duplicate from an array
eg. numbers = [2,1,3,1,4,6,1,8,2,1,3,4]


5. create a program that checks if a word is palindrome
ie. it is the same when you spell it backward
eg. madam, eye

In [19]:
# 1. create a program that displays a multiplication table
# eg. 2 x 1 = 2
#     2 x 2 = 4
# up to 2 x 12 = 24

# NB: Do not write out the table one by one. Use loop.
x = 2
# numbers = [1,2,3,4,5,6,7,8,9,10,11,12]
# for i in numbers:
for i in range(1,13):
#     print( x , "*", i , "=", x*i) 
    print(f"{x} x {i} = {x * i}")


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
2 x 11 = 22
2 x 12 = 24


In [87]:
# 2. create a program that finds the largest of 3 numbers
x = 3
y = 8
z = 9

# if x>=y and x>=z:
#      print({x})
# elif y>=x and y>=z:
#         print("Largest" "=",{y})
# elif z>=x and z>=y:
# #         print(f"Largest {z}")
# #           print(z, "is the largest")
#           print("The largest is ", z)
# else:
#     print("No Largest number")
# What if we have upto 1000 numbers and we are to pick the largest 
# the Psuedo code
#     1. pick first number and compare to second number
#     2. the one that is largest among them, compare it to the next number
#     3. if the same number is larger, it remains the largest
#     4. continuie to the end
x = [100, 56, 0 ,12, 80, 101]
largest = x[0]
largest
# for i in x:
#     if i > largest:
#         largest = i
#         print("the largest is ", largest)



100

In [117]:
# 3.  create a program that take a score and show the grade using if else or match case:
# 90 - 100 ("Grade A")
# 70 - 89  ("Grade B")
# 50 - 69 ("Grade c")
# 30 - 49 ("Grade E")
# 0 - 29  ("Grade E")

grade = input("grade")
if grade >= "90":
    print("A")
else: 
    if grade >="70":
         print("B")
    else: 
        if grade >="50":
             print("C")
        else: 
            if grade >="0":
                 print("E")

grade90
A


In [111]:
grade = input("grade")
if grade >= "90":
    print("A")
elif grade >="70":
         print("B")
elif grade >="50":
             print("C")
else : grade >="0"
print("E")

grade56
C
E


In [90]:
grade = input("grade")
match(grade):
        case _ if grade >= "90": 
            print("A")
        case _ if grade >="70":
             print("B")
        case _ if grade >="50":
             print("C")
        case _  if grade >="30":
             print("D")
        case _  if grade >="0":
             print("E")

grade69
C


In [ ]:
# 4. Create a program that accepts 2 numbers and an operator eg. 5 6, +
# then perform an operation based on what the user enters eg 5 + 6
# if the user enters 2, 8, * it should return 2 * 8
# and show the answer in console

In [64]:
# 3. Create a program that accepts 2 numbers and an operator eg. 5 6, +
# then perform an operation based on what the user enters eg 5 + 6
# if the user enters 2, 8, * it should return 2 * 8
# and show the answer in console
x = float(input("enter first number: "))
y = float(input("enter second number: "))
z = input("enter z (+,  -, /, *, //, %, **): ")
# if z == "+" :
result = {x} {z} {y} 
    print(result)
#                 print(f"{x},{z},{y})
# else: 
#     print("0")


SyntaxError: invalid syntax (2540263961.py, line 9)

In [143]:
# 5. create a program that removes a duplicate from an array
# eg. numbers = [2,1,3,1,4,6,1,8,2,1,3,4]
# method 1
numbers = [2,1,3,1,4,6,1,8,2,1,3,4]
#     print(set(numbers))
# method 2
basket = []
for i in numbers:
    if i not in basket:
        basket.append(i)
print(basket)


[2, 1, 3, 4, 6, 8]


In [149]:
# 5. create a program that checks if a word is palindrome
# ie. it is the same when you spell it backward
# eg. madam, eye

def is_palindrome(word):
    # Remove spaces and convert the word to lowercase for accurate palindrome check
    word = word.replace(" ", "").lower()
    
    # Compare the word with its reverse
    return word == word[::-1]

# Input a word to check if it's a palindrome
word = input("Enter a word: ")

if is_palindrome(word):
    print(f"'{word}' is a palindrome.")
else:
    print(f"'{word}' is not a palindrome.")


Enter a word: eye
'eye' is a palindrome.


In [148]:
def is_palindrome(word):
    word = word.replace(" ", "").lower()

    return word == word[::-1]
word = input("Enter a word: ")
if is_palindrome(word):
    print(f"'{word}' is a palindrome.")
else:
    print(f"'{word}' is not a palindrome.")

Enter a word: eye
'eye' is a palindrome.


In [203]:
def check_palindrome(word):
    reverse_word = word[::-1]
    if word == reverse_word:
        print("Is palindrome")
    else:
        print("Not palindrome")
    
    

In [204]:
check_palindrome("malam")

Is palindrome


In [164]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
operator = input("Enter an operator (+, -, *, /): ")

# Perform the operation based on the operator
if operator == "+":
    result = num1 + num2

Enter the first number: 1
Enter the second number: 1
Enter an operator (+, -, *, /): +


In [24]:
number = 1
x = 2
while number <= 12:
    print(f"{x} x {number} = {x*number}")
    number = number + 1
#      print(f"{x} x {i} = {x * i}")


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
2 x 11 = 22
2 x 12 = 24


In [120]:
grade = input(grade)
match(grade):
        case _ if grade >= 90: 
            print("A")
        case _ if grade >=70:
             print("B")
        case _ if grade >=50:
             print("C")
        case _  if grade >=30:
             print("D")
        case _  if grade >=0:
             print("E")

9059


TypeError: '>=' not supported between instances of 'str' and 'int'

In [150]:
word = "aeye"
word.split("")

ValueError: empty separator

In [178]:
word = input("Enter a word: ") 
reversed_word = word[::-1]
if word == reversed_word:
    print("is palindrom")
else:
    print("Not Palindrom") 

Enter a word: madam
is palindrom


In [185]:
# Function --is a block of code that can be reused and it starts with def

def add_numbers():
    return 2 + 2


In [188]:
add_numbers()

4

In [200]:
# function parameters
def add_numbers(x,y):
    return {x + y}



In [ ]:
def add_numbers(x,y):
    return {x + y}


In [202]:
add_numbers(3,4)

{7}

In [211]:
lambda x, y: x + y



<function __main__.<lambda>(x, y)>

In [220]:
# module --- modules is the process of importing code that are written somewhere and use it in youe code
import calculate
calculate.add_it(3,6)


9

In [221]:
from calculate import *
add_it(7,8)

15

In [235]:
#  Working with file
file = open("newpythonclass", "w")
file.write("This is magical")


15

In [236]:
# ls

In [234]:
# Reading file
file = open("newpythonclass")
file.read()

'This is magical'

In [246]:
file = open("newpythonclass", "w")
file.write("Life is not hard")


16

In [247]:
file = open("newpythonclass", "r")
file.read()

'Life is not hard'

In [248]:
file = open("newpythonclass", "a")
file.write("\nThis is interesting")

20

In [249]:
file = open("newpythonclass", "r")
print(file.read())


Life is not hard
This is interesting


In [250]:
# numpy is a python library for generating sample data and working with multi dimensional arrays

In [251]:
one = [1,2,3,5]
two = [2,3,4,5]
one + two

[1, 2, 3, 5, 2, 3, 4, 5]

In [258]:
# import numpy library and alias it as np
import numpy as np

In [257]:
# using different operator
np.array(one) / np.array(two)

array([0.5       , 0.66666667, 0.75      , 1.        ])

In [259]:
# generate sample data
np.arange(5)

array([0, 1, 2, 3, 4])

In [261]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [262]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [274]:
# generate random data
np.random.rand()

0.3409714756264628

In [276]:
np.random.rand(3,5)

array([[0.92621648, 0.44834142, 0.62778829, 0.33066335, 0.89142384],
       [0.81849078, 0.82884419, 0.27920705, 0.23023762, 0.78918013],
       [0.32620159, 0.23553526, 0.16875957, 0.37673224, 0.63888386]])

In [266]:
matrix = [[1,2,3,4],[5,6,7,8],[4,4,4,7]]

In [267]:
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [4, 4, 4, 7]]

In [270]:
matrix = np.array(matrix)
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 4, 4, 7]])

In [272]:
# numpy array properties
matrix.shape

(3, 4)

In [277]:
matrix.ndim

2

In [278]:
matrix.dtype

dtype('int32')

In [279]:
matrix.size

12

In [283]:
x = np.arange(1,25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [285]:
x.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [286]:
x.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [287]:
x.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [289]:
x.size

24

In [294]:
# randn can generate floating values below 0 and above 1
np.random.randn()

-0.2372632106325324

In [296]:
np.random.randn(10,5)

array([[ 0.45150882,  1.31459127,  0.61488786,  0.87807666,  0.21177101],
       [-1.40848391, -0.20891952,  1.21878375, -0.17011665, -1.64593757],
       [ 0.85472548, -0.44480642, -0.63878559,  1.79122341, -1.01171243],
       [ 1.05111142, -0.8989761 , -1.00446972, -0.31366055,  0.59729604],
       [-0.51259473,  0.69999677,  0.51961695,  1.14812068,  0.38679537],
       [-1.58667652, -0.29769955, -1.03171017, -0.85175895,  0.43779351],
       [ 0.11175238, -0.3703627 ,  0.59275489,  2.5481845 , -0.26896606],
       [ 1.27571639,  0.32863848,  0.88377558,  0.72701947,  0.75945107],
       [ 0.04476162, -1.93558837,  1.2432193 ,  0.16041486, -1.39991046],
       [-2.19339287, -0.19688625,  1.28179144,  0.60896241, -0.31513776]])

In [307]:
np.random.randint(5)

2

In [311]:
np.random.randint(2,21,10)

array([20,  6,  4, 19,  5, 16,  3,  2, 16,  5])

In [314]:
# used to generate evenly spaced floating numbers
np.linspace(1,11)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

In [317]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [318]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [319]:

np.array([1,2,3,4]) + np.array([6,5,5,4])

array([7, 7, 8, 8])

In [320]:
# Broadcasting
np.array([1,2,3,4]) + np.array([6])

array([ 7,  8,  9, 10])

In [321]:
 np.array([6]) + np.array([1,2,3,4])

array([ 7,  8,  9, 10])

In [324]:
a = np.array([[1,2,3], [4,5,6],[2,2,3]])
b = np.array([1,2,3])

In [325]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [326]:
a + b

array([[2, 4, 6],
       [5, 7, 9],
       [3, 4, 6]])

In [327]:
# indexing of numpy
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [330]:
#  indexing
a[1][1]

5

In [342]:
# slicing of numpy
a[1:3,0:2]

array([[4, 5],
       [2, 2]])

In [336]:
# slicing of numpy
a[0:3,1:2]

array([[2],
       [5],
       [2]])

In [348]:
a[:,1:2]

array([[2],
       [5],
       [2]])

In [346]:
## slicing of numpy
a[2:3,0:3]

array([[2, 2, 3]])

In [347]:
a[2:,:]

array([[2, 2, 3]])

In [349]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [358]:
# summing columns
sum(a)

array([ 7,  9, 12])

In [359]:
# summing columns
a.sum(axis=0)

array([ 7,  9, 12])

In [361]:
# sumimg all the numbers
a.sum()

28

In [362]:
# summing roles
a.sum(axis=1)

array([ 6, 15,  7])

In [365]:
# suming a particular column
# for column 2
a.sum(axis=0)[2:]

array([12])

In [366]:
# for column 2
a.sum(axis=0)[1:2]

array([9])

In [367]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 3]])

In [368]:
a>4

array([[False, False, False],
       [False,  True,  True],
       [False, False, False]])

In [371]:
a[a>4]

array([5, 6])

In [388]:
# 1. Create an array of integers from 10 to 50
x = np.arange(10,51)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
import numpy as np

In [387]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0,9)
matrix

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [389]:
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [404]:
# 3. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>
np.random.randn(25)

array([ 1.32307253, -0.51870798, -0.25435408,  0.77665245, -0.92053791,
       -0.4417108 ,  0.19217076,  0.12054089,  0.98850668,  1.14194744,
        1.47584673, -0.31438181, -0.58114655,  1.04518942,  2.41764484,
       -0.74490098, -0.67189505, -0.13919722, -1.2023241 ,  0.35117619,
        1.41418846, -1.88830005,  2.43514735,  0.0210393 , -1.20621246])

In [416]:
# 4. create this matrix

# array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
#        [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
#        [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
#        [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
#        [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
#        [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
#        [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
#        [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
#        [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
#        [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

np.linspace(0.01,1,100)


array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [417]:
# 5. Create an array of 20 linearly spaced points between 0 and 1:
# Like the one below
# array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
#        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
#        0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
#        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])
# NB: use this data to solve subsequent challenges

# data = np.arange(1,26).reshape(5,5)
# data


np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [418]:
data = np.linspace(0,1,20)

In [423]:
data = np.arange(1,26)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [6]:
# 7. bring out the follow from data above
# array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])
data = np.arange(1,26).reshape(5,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [452]:
data[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [459]:
# 8. produce the output below from the data above
# array([[ 2],
#        [ 7],
#        [12]])
data[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [460]:
# 9. produce the output below from the data above
# array([21, 22, 23, 24, 25])
data[4,0:]

array([21, 22, 23, 24, 25])

In [7]:
# 10. Get the sum of all the values in data
np.sum(data)

325

In [9]:
# 11. Get the sum of all the columns in data
np.sum(data, axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
np.